services:
  db:
    image: mongo:5
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jguanolema
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db